name = "lineoa-ai-admin"
main = "workers/webhook/index.js"
compatibility_date = "2024-06-20"

[vars]
# SUPABASE_URL = ""
# SUPABASE_ANON_KEY = ""

[[d1_databases]]
binding = "LINEOA_DB"
database_name = "lineoa_db"
database_id = "18e742b2-fead-454a-b468-d81051b7f037"

[[kv_namespaces]]
binding = "AI_CONFIG"
id = "f090090bea4f4d11a4f07d9793df41d2"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "dawnbags-lineoa"
